version: 2.1

orbs:
  cypress: cypress-io/cypress@3.4.0

jobs:
  deploy-to-render-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Staging
          # In the following command, we are echoing a message to the console and then using curl to send a GET request to the Render Deploy Hook that is an environment variable in CircleCI.
          command: |
            echo "Deploying to Render Staging"
            curl $RENDER_STAGING_DEPLOYHOOK

workflows:
  run-tests-and-deploy-to-staging:
    jobs:
      - cypress/run:
          name: run-e2e-tests
          environment:
            MONGODB_URI: mongodb+srv://kvance:password1234@cluster0.ugwti.mongodb.net/wordGuessingGame?retryWrites=true&w=majority&appName=Cluster0
          start-command: npm run start:dev
            cypress-command: npx wait-on@latest tcp:3001 && npx cypress run --parallel --browser electron --headless --baseUrl http://localhost:3001
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
      - deploy-to-render-staging:
          requires:
            - run-e2e-tests
            - run-component-tests
          filters:
            branches:
              only: main
