version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

workflows:
  run-tests:
    jobs:
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --componentversion: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  deploy-to-render-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Staging
          command: |
            echo "Deploying to Render Staging"
            curl $RENDER_STAGING_DEPLOYHOOK

workflows:
  run-tests-and-deploy-to-staging:
    jobs:
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
      - deploy-to-render-staging:
          requires:
            - run-component-tests
          filters:
            branches:
              only: main
