version: 2.1

# 🔑 A CircleCI orb is a reusable snippet of code that helps to automate a repeated process and makes it easy to integrate with third-party tools. Here, we can use the Cypress orb to make it easier to run our Cypress tests in our application:
orbs:
  # cypress orb simplifies the process of running cypress tests in CircleCI by providing a set of pre-configured commands and executors, reducing the amount of configuration needed to run cypress tests.
  cypress: cypress-io/cypress@3.3.1


workflows:
  run-tests:
    jobs:
      - cypress/run:
          name: run-e2e-tests
          # 🔑 The `cypress-command` parameter allows us to pass in the Cypress command that we want to run. 
          cypress-command: npx cypress run --browser electron --headless
          # 🔑 The `start` parameter allows us to specify the command that we want to run to start our application.
          start-command: npm run start:dev
          