#  🔑 Our configuration file is YAML, which is a data serialization language. We use version `2.1` in our CircleCI configuration:
version: 2.1

# 🔑 We first define our jobs. Our configuration just has the `hello-world-job`:
# In CircleCI, jobs are a collection of steps that are executed together. The job is executed within a container or a virtual machine. 
jobs:
  # Our hello-world-job just has one step where it runs the command echo "Hello, World" in our CircleCI base container.
  hello-world-job:
  # In this example, we are using a docker container to run our job steps. Docker is a platform that allows you to create, manage, and run containers. A container is a unit of software that packages up code and all dependencies so that that code can be run quickly and reliably despite the computing environment. Docker creates a container using an image.
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Hello, World!"

# 🔑 We then define our workflows. Without a workflow, our job definitions would not run by themselves.
workflows:
  hello-world-workflow:
    jobs:
    # Note that the - symbol denotes a possible list of items for a certain value. We have a - before our job name, because jobs can contain a list of jobs to run.
      - hello-world-job
